export const LUZON_PROVINCES = [
  "abra",
  "albay",
  "apayao",
  "aurora",
  "bataan",
  "batanes",
  "batangas",
  "benguet",
  "bicol",
  "bulacan",
  "cagayan",
  "camarines norte",
  "camarines sur",
  "catanduanes",
  "cavite",
  "ifugao",
  "ilocos norte",
  "ilocos sur",
  "isabela",
  "kalinga",
  "la union",
  "laguna",
  "masbate",
  "mountain province",
  "nueva ecija",
  "nueva vizcaya",
  "palawan",
  "pangasinan",
  "quezon",
  "quirino",
  "rizal",
  "sorsogon",
  "tarlac",
  "zambales",
];

export const VISAYAS_PROVINCES = [
  "aklan",
  "antique",
  "bohol",
  "capiz",
  "cebu",
  "eastern samar",
  "guimaras",
  "iloilo",
  "leyte",
  "negros occidental",
  "negros oriental",
  "northern samar",
  "samar",
  "western samar",
  "southern leyte",
  "siquijor",
];

export const MINDANAO_PROVINCES = [
  "agusan del norte",
  "agusan del sur",
  "basilan",
  "bukidnon",
  "camiguin",
  "compostela valley",
  "davao del norte",
  "davao del sur",
  "davao occidental",
  "davao oriental",
  "dinagat islands",
  "lanao del norte",
  "lanao del sur",
  "maguindanao",
  "misamis occidental",
  "misamis oriental",
  "north cotabato",
  "south cotabato",
  "southern cotabato",
  "sultan kudarat",
  "sulu",
  "surigao del norte",
  "surigao del sur",
  "tawi-tawi",
  "zamboanga del norte",
  "zamboanga del sur",
  "zamboanga sibugay",
];
